version '2.1'
services:
  ftp:
    image: delfer/alpine-ftp-server
    network_mode: host
#    ports:
#      - 21:21
#      - 21000-21010:21000-21010
    environment:
      - USERS=one|1234|/home/one|10001 two|12345|/home/two|122345
    volumes:
      - ./one:/home/one
      - ./two:/home/two