##############################################################################
#
# Vagrant file for Docker env with public repo
#
##############################################################################
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "ubuntu-docker"
  # Bridge network with phisical NIC for access from system  host
  config.vm.network "public_network"
  # require plugin https://github.com/leighmcculloch/vagrant-docker-compose
  config.vagrant.plugins = "vagrant-docker-compose"

  # install docker and docker-compose
  config.vm.provision :docker
  config.vm.provision :docker_compose

  #config.vm.provider "virtualbox" do |vb|
  #  vb.customize ["modifyvm", :id, "--ioapic", "on"]
  #  vb.customize ["modifyvm", :id, "--memory", "2048"]
  #  vb.customize ["modifyvm", :id, "--cpus", "2"]
  #end
 
  config.vm.provider "virtualbox" do |v|
    v.name = "docker"
    v.cpus = 2
    v.memory = "2048"
    v.gui = false
  end

end
